routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PostController;
use App\Models\Post;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//This route is for logging out.
Route::get('/logout', [PostController::class, 'logout']);

//This route is for creation of a new post:
Route::get('/posts/create', [PostController::class, 'createPost']);

//This route is for saving the post on our database:
Route::post('/posts', [PostController::class, 'savePost']);

//Only logged in users can read all posts
Route::middleware(['auth'])->group(function () {
    //This route is for the list of post on our database:
    Route::get('/posts', [PostController::class, 'showPosts'])->name('posts.show');

    //This route will return a view of a specific post matching the URL parameter ID
    Route::get('/posts/{id}', [PostController::class, 'show'])->name('posts.show');
});

//Route that will show the welcome page showing Featured Posts, if any:
Route::get('', [PostController::class, 'welcome']);

//Define that will return a view containing only the aithenticated user's post
Route::get('/myPosts', [PostController::class, 'myPosts']);

//Route for editing a post
Route::get('/posts/{id}/edit', [PostController::class, 'edit'])->name('posts.edit');

//Route for updating a post
Route::put('/posts/{id}', [PostController::class, 'update'])->name('posts.update');

//Route for archiving a post
Route::delete('/posts/{id}', [PostController::class, 'archive'])->name('posts.archive');

//Define a web rout that will call the function for liking and unliking a specific post:
Route::put('/posts/{id}/like', [PostController::class, 'like']);

// Route to handle commenting
Route::post('/posts/{id}/comment', [PostController::class, 'comment'])->name('posts.comment');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    // Define the relationship with the User model
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    // Define the relationship with the PostLike model
    public function likes()
    {
        return $this->hasMany(PostLike::class);
    }

    // Define the relationship with the PostComment model
    public function comments()
    {
        return $this->hasMany(PostComment::class);
    }

    // Define an accessor to get the count of comments
    public function getCommentsCountAttribute()
    {
        return $this->comments()->count();
    }

    // Define an accessor to get the count of likes
    public function getLikesCountAttribute()
    {
        return $this->likes()->count();
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Illuminate\Support\Facades\Auth;

use App\Models\Post;
use App\Models\PostLike;
use App\Models\PostComment;


class PostController extends Controller
{
    // Controller for user logout
    public function logout()
    {
        Auth::logout();
        return redirect('/login');
    }

    // Action to return a view containing a form for a blog post creation
    public function createPost()
    {
        return view('posts.create');
    }

    public function savePost(Request $request)
    {
        if (Auth::user()) {
            $post = new Post;

            $post->title = $request->input('title');
            $post->content = $request->input('content');
            $post->user_id = Auth::user()->id;

            $post->save();

            return redirect('/posts');
        } else {
            return redirect('/login');
        }
    }

    // Controller to return all active blog posts
    public function showPosts()
    {
        $activePosts = Post::where('isActive', true)->get();
        return view('posts.showPosts')->with('posts', $activePosts);
    }


    // Controller to return 3 random active posts as Featured Posts in Welcome Page
    public function welcome()
    {
        // Retrieve all active posts
        $activePosts = Post::where('isActive', true)->get();

        // Check if there are at least 3 active posts
        // If yes, select 3 random active posts; otherwise, select all available active posts
        $randomPosts = $activePosts->count() >= 3 ? $activePosts->random(3) : $activePosts;

        // Pass the random featured posts to the welcome view
        return view('welcome')->with('randomPosts', $randomPosts);
    }


    // Action for showing only the posts authored by authenticated user
    public function myPosts()
    {
        if (Auth::user()) {
            $posts = Auth::user()->posts;
            return view('posts.showPosts')->with('posts', $posts);
        } else {
            return redirect('/login');
        }
    }

    // Action that will return a view showing a specific post using the URL parameter $id to query for the database entry to be shown
    // public function show($id)
    // {
    //     // Find the Post record with the given $id or throw an exception if not found
    //     $post = Post::findOrFail($id);

    //     // Pass the retrieved Post model instance to the 'posts.show' view using the compact function to create an associative array with the variable name 'post'
    //     return view('posts.show', compact('post'));
    // }

    public function show($id)
    {
        // Find the Post record with the given $id or throw an exception if not found
        $post = Post::findOrFail($id);

        // Load the comments relationship
        $post->load('comments');

        // Pass the retrieved Post model instance to the 'posts.show' view
        return view('posts.show', compact('post'));
    }


    // Action that will edit a specific post
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view('posts.edit', compact('post'));
    }

    // Action that will update the edited post
    public function update(Request $request, $id)
    {
        $post = Post::findOrFail($id);

        // Update the title and content of the Post with data from the incoming Request
        $post->title = $request->input('title');
        $post->content = $request->input('content');
        $post->save();

        return redirect()->route('posts.show', ['id' => $post->id])->with('success', 'Post updated successfully.');
    }

    // Action that will archive a post
    public function archive($id){
        $post = Post::find($id);
        $posts = Post::all();

        $post->isActive = false;
        $post->save();

        
        return redirect('/posts')->with('archived', 'Post archived successfully.');
    }

    public function like($id){
        $post = Post::find($id);

        if($post->user_id != Auth::user()->id){

            if($post->likes->contains("user_id", Auth::user()->id)){
                //delete the like record made by the user before
                PostLike::where('post_id', $post->id)->where('user_id', Auth::user()->id)->delete();
            }else{
                //create a new like record to like this post
                //instantiate a new PostLike object from the Postlike model
                $postlike = new PostLike;
                //define the properties of the $postlike
                $postlike->post_id = $post->id;
                $postlike->user_id = Auth::user()->id;

                //save this postlike object in the database
                $postlike->save();
            }
        }

        return redirect("/posts/$id");
    }


    public function comment(Request $request, $id)
    {
        // Validate input
        $request->validate([
            'content' => 'required',
        ]);

        // Create a new comment
        $comment = new PostComment();
        $comment->content = $request->input('content');
        $comment->post_id = $id;
        $comment->user_id = auth()->user()->id;
        $comment->save();

        return redirect()->back()->with('success', 'Comment added successfully.');
    }


}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('tabName')
    Create Post
@endsection

@section('content')

	
	<form class="col-3 bg-warning p-5 mx-auto" method="POST" action="/posts">
		<!-- CSRF stands for Cross-Site Request Forgery. It is form of attact where malicious users may send malicious request while pretending to be authorize user. Laravel uses token to detect if form input request have not been tampered with. -->
		@csrf
		<div class="form-group">
			<label for="title">Title:</label>
			<input type="text" name="title" class="form-control" id="title" />
		</div>

		<div class="form-group mt-2">
			<label for="content">Content:</label>
			<textarea class="form-control" id="content" name="content" rows=3></textarea>
		</div>

		<div class="mt-2 mx-auto">
			<button class="btn btn-primary">Create Post</button>
		</div>
	</form>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('tabName')
    Edit Post
@endsection

@section('content')
<div class="container col-6 mx-auto">

    <!-- Edit Post Form -->
    <div>
        <h3>Edit Post</h3>
        <p class = "card-subtitle mb-3 text-muted">Created at: {{$post->created_at}}</p>
        <form method="POST" action="{{ route('posts.update', ['id' => $post->id]) }}">
            @csrf
            @method('PUT')

            <!-- Title Input -->
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" id="title" name="title" value="{{ $post->title }}" required>
            </div>

            <!-- Content Textarea -->
            <div class="form-group mt-2">
                <label for="content"> Content</label>
                <textarea class="form-control" id="content" name="content" rows="5" required>{{ $post->content }}</textarea>
            </div>

            <!-- Update Button -->
            <button type="submit" class="btn btn-primary mt-2">Update Post</button>
        </form>
    </div>
</div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('tabName')
    {{$post->title}}
@endsection

@section('content')
<div class="card col-md-8 col-lg-8 mx-auto">
    <div class="card-body">
        <h2 class="card-title">{{$post->title}}</h2>
        <p class="card-subtitle text-muted">Author: {{$post->user->name}}</p>
        <p class="card-subtitle text-muted mb-3">Created at: {{$post->created_at}}</p>
        <h4>Content:</h4>
        <p class="card-text">{{$post->content}}</p>

        <!-- Likes and Comment Counts -->
        <p style="font-size: 12px;">Likes: {{$post->likes_count}} | Comments: {{$post->comments->count()}}</p>

        <!-- Like Button (if not the author of the post) -->
        @if(Auth::user() && Auth::id() != $post->user_id)
            <form class="d-inline" method="POST" action="/posts/{{$post->id}}/like">
                @method('PUT')
                @csrf
                @if($post->likes->contains('user_id', Auth::id()))
                    <button class="btn btn-danger">Unlike</button>
                @else
                    <button class="btn btn-success">Like</button>
                @endif
            </form>
        @endif

        <!-- Comment Button -->
        @if(Auth::user())
            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#commentModal">Comment</button>
        @endif

        <br><br>

        <a href="/posts" class="card-link">View all posts</a>
    </div>
</div>

<!-- Comment Modal -->
<div class="modal" tabindex="-1" id="commentModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" action="{{ route('posts.comment', ['id' => $post->id]) }}">
                @csrf
                <div class="modal-header">
                    <h5 class="modal-title">Leave a comment</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <textarea name="content" rows="3" class="form-control" placeholder="Your comment..."></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Comment</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- List of Comments -->
@if($post->comments->count() > 0)
    <div class="mt-5 col-md-8 col-lg-8 mx-auto">
        <h4 class="mb-3">Comments</h4>
        @foreach($post->comments as $comment)

            <p class="card-subtitle" style="font-size: 12px;">Posted by: {{$comment->user->name}}</p>
            <div class="card my-1">
                <div class="card-body mx-auto">
                    <h6 class="card-text">{{$comment->content}}</h6>
                </div>
            </div>
            <p class="card-subtitle text-muted text-end mb-3" style="font-size: 12px;">{{$comment->created_at->format('F d, Y H:i:s')}}</p>

        @endforeach
    </div>
@else
    <p class="mt-4">No comments yet.</p>
@endif


@endsection

resources/views/posts/showPosts.blade.php
@extends("layouts.app")

@section('tabName')
    Newsfeed
@endsection

@section('content')
    <h3>Newsfeed</h3>
    @if(count($posts)>0)
        @foreach($posts as $post)
            
            <div class = "card text-center col-sm-3 col-md-3 mx-auto mt-2">
                <div class = "card-body">
                    <h4 class = "card-title mb-3">
                        <a href="/posts/{{$post->id}}">{{$post->title}}</a></h4>
                    <h6 class = "card-text mb-3">Author: {{$post->user->name}}</h6>
                    <p class = "card-subtitle mb-3 text-muted">Created at: {{$post->created_at}}</p>
                </div>
                @if(Auth::user())
                    <!-- if the authenticated user is the author of this blog post -->
                    @if(Auth::user()->id == $post->user_id)
                        <div class = "card-footer">
                            <form method = "POST" action = "/posts/{{$post->id}}">
                                @method('DELETE')
                                @csrf
                                <a href="/posts/{{$post->id}}/edit" class = "btn btn-primary">Edit Post</a>
                                <button class = "btn btn-danger">Delete Post</button>
                            </form>
                        </div>

                    @endif
                @endif
                
            </div>
        
        @endforeach
    @else
        <div>
            <h2>There are no posts to show</h2>
            <a href="/posts/create" class = "btn btn-info">Create Post</a>
        </div>
    @endif
@endsection